### ISSUE TITLE
Element index - Ouija Board

### ISSUE THREAD

**Issue by matuzo** [matuzo/HTMHell#72]
I want to add an element index to the website. The content isn't ready yet, but I've already added quite a lot and the basic page structure is also ready.

You can find the WIP in [this branch](https://github.com/matuzo/HTMHell/blob/element-index) and [file](https://github.com/matuzo/HTMHell/blob/element-index/hell/elements.njk).

Here's what I need: 

I want the list of of letters to look like a Ouija Board. 

- [ ] 2 rows of letters aligned along an arc.
- [ ] the mouse pointer should change
- [ ] optional: additional stylistic elements that make it look more like an actual board (see image)
- [ ] optional: JS to make the cursor snap when you're close to a letter
- [ ] optional: make the mouse cursor always point to the top center of the board.

![91wL628K5ML _AC_SL1500_](https://user-images.githubusercontent.com/1496761/132816386-8b777917-dcd2-4d7d-b9a6-fb726b23d335.jpg)

[Ouija Board Google Images](https://www.google.com/search?q=ouija+board&client=firefox-b-d&channel=trow5&sxsrf=AOaemvIH6mCnn_kySx-cmrbnkc0HdqDhoA:1631258597708&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj-zILq7_PyAhWFgP0HHTDfAUcQ_AUoAXoECAEQAw&biw=1280&bih=1330#imgrc=anNmjAkt-pr-SM)

**Comment by simevidas** [comment]
Letters along arc is doable with SVG https://twitter.com/argyleink/status/1410589757084667912

**Comment by ahmadalfy** [comment]
I'd give it a shot

**Comment by SaptakS** [comment]
I have started working on this as well.

**Comment by ahmadalfy** [comment]
This is what I am up to until now

![image](https://user-images.githubusercontent.com/87611/132888612-d3e8431f-c0eb-4ad0-baf6-5c4626be72dd.png)

This is without the outline

![image](https://user-images.githubusercontent.com/87611/132889089-746bc8f0-e592-4c29-b378-14a9c3bdd26f.png)

@matuzo is that the right direction 😅

**Comment by matuzo** [comment]
@ahmadalfy that looks fantastic! Do the links still work, even tough they're overlapping?

**Comment by ahmadalfy** [comment]
Yes they work. This is how the links look like with yellow background applied to the `a` tag. I could ad some additional width to facilitate pointing

![image](https://user-images.githubusercontent.com/87611/132889834-39bb24ca-bde8-485f-813d-c2211c5d7802.png)

**Comment by ahmadalfy** [comment]
This is starting to look hellish

![image](https://user-images.githubusercontent.com/87611/132891469-c77911de-9fb8-4c8d-a3c0-51a14f73717b.png)

**Comment by matuzo** [comment]
You're killing it @ahmadalfy, great work! @SaptakS would it make sense that the two of you get in touch and share your work to get the best out of it?

**Comment by SaptakS** [comment]
Makes sense. I see @ahmadalfy has proceeded the exact same way as I was doing  by rotating each alphabet. I was taking inspiration [from a similar codebase](https://codepen.io/team/css-tricks/pen/a5b2847df84a9e88f3d3c1544d1681ad).  Happy to collaborate on the next steps or review the code once you are done, whichever makes more sense.

**Comment by ahmadalfy** [comment]
What do you think about having three rows for mobile?

**Comment by SaptakS** [comment]
I think 3 row is a good idea for mobile. This might be too clumsy in mobile. I think we will need to have lesser alphabets in the third row though to allow for proper spacing.

**Comment by ahmadalfy** [comment]
> I think we will need to have lesser alphabets in the third row though to allow for proper spacing.

You mean on mobile or on desktop as well?

@matuzo pardon me, I allowed my self to go wild with this one

![image](https://user-images.githubusercontent.com/87611/132895209-2b3907df-346c-4a78-84df-20a45fd6d9f7.png)

![image](https://user-images.githubusercontent.com/87611/132895364-91619c21-82c0-42fd-b5df-292ed769173a.png)

This is the focus style and it aligns perfectly with each anchor. Paste this code on your CSS to try it

```css


** { outline: 1px solid red; }

.ouija-letters {
    margin: 0 auto;
    padding: 0;
    list-style: none;
    text-align: center;
    display: flex;
    flex-wrap: wrap;
  position: relative;
  width: 400px;
  border-radius: 50%;
  transform: rotate(-64deg);
    height: 400px;
}

.ouija-letters::before {
    content: '';
    position: absolute;
        background: url(https://img.freepik.com/free-photo/texture-old-faded-vintage-paper-beige-retro-background-grunge-paper-with-spots-streaks_213524-157.jpg?size=626&ext=jpg);
    width: 600px;
    height: 300px;
  transform: rotate(64deg);
    left: -100px;
    top: 50px;
}

.ouija-letters li {
    z-index: 1;
}

.ouija-letters li:focus-within {
    z-index: 2;
}

.ouija-letters li a {
    display: inline-block;
    position: relative;
}

.ouija-letters li a:focus {
    outline: none;
}

.ouija-letters li a:focus::before {
    background: url(https://i.imgur.com/piBnrtK.png);
    background-size: 100% auto;
    position: absolute;
    width: 120px;
    height: 160px;
    content: '';
    background-repeat: no-repeat;
    top: -45px;
    left: -52px;
    z-index: 1;
}

.ouija-letters li {
  font: 26px Monaco, MonoSpace;
  height: 300px;
  position: absolute;
  left: 0;
  top: -10px;
  transform-origin: bottom center;
}

.ouija-letters li:nth-child(n + 14) { left: 0; top: 40px ; height: 250px }



.ouija-letters li:nth-child(1) {
	transform: rotate(9.23077deg);
}

.ouija-letters li:nth-child(2) {
	transform: rotate(18.46154deg);
}

.ouija-letters li:nth-child(3) {
	transform: rotate(27.69231deg);
}

.ouija-letters li:nth-child(4) {
	transform: rotate(36.92308deg);
}

.ouija-letters li:nth-child(5) {
	transform: rotate(46.15385deg);
}

.ouija-letters li:nth-child(6) {
	transform: rotate(55.38462deg);
}

.ouija-letters li:nth-child(7) {
	transform: rotate(64.61538deg);
}

.ouija-letters li:nth-child(8) {
	transform: rotate(73.84615deg);
}

.ouija-letters li:nth-child(9) {
	transform: rotate(83.07692deg);
}

.ouija-letters li:nth-child(10) {
	transform: rotate(92.30769deg);
}

.ouija-letters li:nth-child(11) {
	transform: rotate(101.53846deg);
}

.ouija-letters li:nth-child(12) {
	transform: rotate(110.76923deg);
}

.ouija-letters li:nth-child(13) {
	transform: rotate(120deg);
}


.ouija-letters li:nth-child(14) {
	transform: rotate(9.23077deg);
}

.ouija-letters li:nth-child(15) {
	transform: rotate(18.46154deg);
}

.ouija-letters li:nth-child(16) {
	transform: rotate(27.69231deg);
}

.ouija-letters li:nth-child(17) {
	transform: rotate(36.92308deg);
}

.ouija-letters li:nth-child(18) {
	transform: rotate(46.15385deg);
}

.ouija-letters li:nth-child(19) {
	transform: rotate(55.38462deg);
}

.ouija-letters li:nth-child(20) {
	transform: rotate(64.61538deg);
}

.ouija-letters li:nth-child(21) {
	transform: rotate(73.84615deg);
}

.ouija-letters li:nth-child(22) {
	transform: rotate(83.07692deg);
}

.ouija-letters li:nth-child(23) {
	transform: rotate(92.30769deg);
}

.ouija-letters li:nth-child(24) {
	transform: rotate(101.53846deg);
}

.ouija-letters li:nth-child(25) {
	transform: rotate(110.76923deg);
}

.ouija-letters li:nth-child(26) {
	transform: rotate(120deg);
}
```

Source image is [here](https://www.vhv.rs/viewpic/iobmTxw_transparent-ouija-board-clipart-ouija-board-planchette-svg/) for attribution
